# Generated by Django 5.0.14 on 2026-03-07 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        help_text="A unique public-facing identifier for this order (max 16 characters).",
                        max_length=16,
                        verbose_name="public ID",
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("AVIA", "Avia"),
                            ("EXPRESS", "Express"),
                            ("AUTO", "Auto"),
                        ],
                        default="AUTO",
                        help_text="The method used to deliver this order (Avia, Express, or Auto).",
                        max_length=16,
                        verbose_name="delivery type",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("HALF", "Half"), ("FULL", "Full")],
                        default="FULL",
                        help_text="Whether the order is paid in full or in two installments (Half).",
                        max_length=16,
                        verbose_name="payment type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SAVED", "Saved"),
                            ("REVIEWED", "Reviewed"),
                            ("ORDERED", "Ordered"),
                        ],
                        default="SAVED",
                        help_text="Current processing status of the order.",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        help_text="The user who placed this order.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ordered by",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["public_id"], name="order_public_id_idx"),
                    models.Index(fields=["status"], name="order_status_idx"),
                ],
            },
        ),
    ]
