# Generated by Django 5.0.14 on 2026-03-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("ON_REVIEW", "On review"),
                    ("REVIEWED", "Reviewed"),
                    ("ORDERED", "Ordered"),
                    ("DELIVERED", "Delivered"),
                ],
                default="ON_REVIEW",
                help_text="Current processing status of the order.",
                max_length=16,
                verbose_name="status",
            ),
        ),
    ]
