# Generated by Django 5.0.14 on 2026-03-07 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The name or title of the product (max 120 characters).",
                        max_length=120,
                        verbose_name="title",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Product image file.",
                        upload_to="products",
                        verbose_name="image",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantity of this product in the order.",
                        verbose_name="amount",
                    ),
                ),
                (
                    "expected_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="The anticipated price of the product before confirmation.",
                        max_digits=12,
                        verbose_name="expected price",
                    ),
                ),
                (
                    "actual_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="The final confirmed price of the product. Leave blank if not yet known.",
                        max_digits=12,
                        null=True,
                        verbose_name="actual price",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Any additional notes or remarks about this product.",
                        null=True,
                        verbose_name="notes",
                    ),
                ),
                (
                    "include_in_order",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this product should be included when processing the order.",
                        verbose_name="include in order",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The order this product belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ["title"],
                "indexes": [
                    models.Index(
                        fields=["include_in_order"], name="product_include_idx"
                    )
                ],
            },
        ),
    ]
