# Generated by Django 5.0.14 on 2026-03-15 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-updated_at", "-created_at"],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="title",
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Link to the product page (e.g. Taobao, 1688, etc.)",
                null=True,
                verbose_name="product link",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_id",
            field=models.CharField(
                default=1, editable=False, max_length=8, verbose_name="Short ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
    ]
